#Messages
no-account-found: "&bYou have no account"

#Gui
enable-gui: true
open-gui-on-commands: true

#Without ChatColor formatting
currency-format:  "<amount> ores"

diamond-nugget-name: "&bDiamond Ore Nugget"
diamond-nugget-lore:
  - "&bA 1/10 of a diamond ore."

main-menu-title: "&bMain Menu"
account-menu-title: "&bAccount Menu"
public-balance-menu-title: "&bPublic Balance Menu"
languages-menu-title: "&bLanguages Menu"
balance-menu-title: "&bBalance Menu"
withdraw-menu-title: "&bWithdraw Menu"
deposit-menu-title: "&bDeposit Menu"
transfer-menu-title: "&bTransfer Menu"
transfer-player-selector-menu-title: "&bTransfer Player Selector Menu"