name: Diore
version: '${project.version}'
main: ximronno.diore.Diore
softdepend: [Vault, PlaceholderAPI]
api-version: '1.19'
commands:
    balance:
      description: Show your balance and make transactions, use /balance help to get subcommands
      usage: /balance
      aliases:
      - bal
      permission: diore.balance
    config:
      description: Manage the config
      usage: /config
      permission: diore.config
permissions:
  diore.balance:
    default: true
  diore.config:
    default: op