# Thanks for using Diore!
# For more info, check wiki https://github.com/Ximronno/Diore/wiki
diamond_nugget_name: "Diamond nugget" #Diamond nugget item name
use_diamonds: false #Use diamonds instead of diamonds ores
use_diamond_nuggets: true #Use diamonds nuggets instead of regular diamonds, doesn't work if use_diamonds is true
general:
  max_withdraw: 25000
  default_balance: 0.0
  enable_gui: true
on_death:
  killer_steal: false
  steal_perc: 33
  min_amount_to_steal: 0.1
save:
  enabled: true #Enables auto saving
  cooldown_minutes: 5 #Auto save interval in minutes
  load_saved_accounts: false #Loads all saved accounts in account_data folder, can crash server at start if you have a lot of accounts!
  max_saved_transactions: 25 #Max saved transactions in players account data, lower if you have lots of players
  save_missing_paths: false #Saves all missing paths, should not save anything with pre-configured messages, helps with new languages creation
console:
  use_logger: true #Logs to console practically every important action
lang:
  default: en_us #Default language, you can change it to other language that is in messages folder
  try_detect_client: true #Tryes to set account language with clients language, only when player doesn't have an account
sql: #Only MySQL is supported!
  enabled: false
  host: localhost
  port: 3306
  database: diore #Must be created before using it!
  username: root
  password: pass
  load_delay: 0
  always_load_on_join: false
hooks:
  vault:
    enabled: true
  placeholderapi:
    enabled: true